dubbo:
  application:
    id: spring-cloud-alibaba-dubbo-provider
    name: spring-cloud-alibaba-dubbo-provider
    qosEnable: false
  scan:
    base-packages: cn.springcloud.gray.dubbo.service
  protocols:
    dubbo:
      port: 20881

feign:
  hystrix:
    enabled: true

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata