spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: admin
  cloud:
    nacos:
      discovery:
        server-addr: 47.114.50.99:8010
        namespace: 77fb94a8-3c81-49d5-acbf-e59e2b21d3b6
#        server-addr: 192.168.10.173:8848
#        server-addr: 47.114.50.99:8010
#        namespace: 77fb94a8-3c81-49d5-acbf-e59e2b21d3b6
#        ip: 192.168.10.173
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # service-a
        - id: service-a
          uri: lb://service-a
          predicates:
            - Path=/ser-a/**
          filters:
            - StripPrefix=1
            # 限流配置
#            - name: RequestRateLimiter
#              args:
#                key-resolver: '#{@uriKeyResolver}'
#                redis-rate-limiter.replenishRate: 500
#                redis-rate-limiter.burstCapacity: 1000
            # 降级配置
#            - name: Hystrix
#              args:
#                name: default
#                fallbackUri: 'forward:/fallback'
    stream:
      bindings:
        GrayEventInput:
          group: zuul
          destination: gray_event
          consumer:
            concurrency: 1 #并发数
        #            max-attempts: 1
      #        GrayEventOutput:
      #          destination: gray-event
      rabbit:
        bindings:
          GrayEventInput:
            consumer:
              maxConcurrency: 1 #并发数
              #              prefetch: 1 #从mq一次获取消息的数量
              #              requeueRejected: true #spring cloud stream 如果出现异常， 是否需要重新投递消息， false表示丢弃。  也有相应的Exception， true-MessageRejectedWhileStoppingException false-AmqpRejectAndDontRequeueException
              #              auto-bind-dlq: true
              acknowledgeMode: AUTO
server:
  port: 20401
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eureka:
    enabled: true
hystrix:
  threadpool:
    # 这是默认的配置
    default:
      coreSize: 10
      maxQueueSize: 200
      queueSizeRejectionThreshold: 2
  command:
    service-a:
      circuitBreaker:
        enabled: true
        forceOpen: true
gray:
  enabled: true
  hystrix:
    enabled: true
  server:
    url: http://gray-server
#    url: http://192.168.10.173:20202
    loadbalanced: true
    retryable: true
  client:
    runenv: web
    serviceUpdateIntervalTimerInMs: 5000
    serviceInitializeDelayTimeInMs: 10000
  holdout-server:
    enabled: true
  request:
    track:
      definitionsUpdateIntervalTimerInMs: 5000
      definitionsInitializeDelayTimeInMs: 10000
      web:
        track-definitions:
        #          - name: HttpIP
        #          - name: HttpMethod
        #          - name: HttpURI
        #          - name: HttpReceive
        #          - name: HttpHeader
        #          - name: HttpParameter
        #            value: version,test
        path-patterns: /*
  load:
    enabled: false
logging:
  level:
    cn:
      springcloud:
        gray: error

