server:
  port: 8058
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gray-server

  #通用数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.100.254.140:3306/gray_server01?charset=utf8mb4&useSSL=false
    username: root
    password: loit2019ABC
    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  # JPA 相关配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: admin
  cloud:
    nacos:
      discovery:
        server-addr: 47.114.50.99:8010
        namespace: 77fb94a8-3c81-49d5-acbf-e59e2b21d3b6
        #        server-addr: 192.168.10.173:8848
        #        server-addr: 47.114.50.99:8010
        #        namespace: 77fb94a8-3c81-49d5-acbf-e59e2b21d3b6
        ip: 192.168.10.173
    stream:
      bindings:
        GrayEventOutput:
          contentType: application/x-java-serialized-object
          destination: gray_event
          rabbit:
            bindings:
              GrayEventInput:
                consumer:
                  maxConcurrency: 1 #并发数
                  prefetch: 1 #从mq一次获取消息的数量
                  requeueRejected: true #spring cloud stream 如果出现异常， 是否需要重新投递消息， false表示丢弃。  也有相应的Exception， true-MessageRejectedWhileStoppingException false-AmqpRejectAndDontRequeueException
                  auto-bind-dlq: true
                acknowledgeMode: AUTO
          acknowledgeMode: MANUAL
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/
    registry-fetch-interval-seconds: 5

gray:
  server:
    cluster:
      #      synchro:
      #        enable: false
      peerNodes:
        - host: localhost
          port: 8058
        - host: localhost
          port: 8059
    evictionIntervalTimerInMs: 30000
    instance:
      normalInstanceStatus: STARTING,UP,OUT_OF_SERVICE
      eviction:
        enabled: true
        evictionIntervalTimerInMs: 86400000
        evictionInstanceStatus: DOWN,UNKNOWN
        lastUpdateDateExpireDays: 1